### ISSUE TITLE
How to obtain the related datasets?

### ISSUE THREAD

**Issue by netivs** [MinseungKo/Load_PV_Forecasting#1]
Could you upload the related datasets or offer me a guideline how to obtain the related datasets? Thanks!

**Comment by MinseungKo** [comment]
You can get each data as followings:
Solar data of ISO New England (ISO-NE): https://www.iso-ne.com/isoexpress/web/reports/operations/-/tree/daily-gen-fuel-type
Load data of ISO-NE: https://www.iso-ne.com/system-planning/system-forecasting/load-forecast
Weather data: https://sam.nrel.gov/weather-data.html
